# Generated by Django 3.2.2 on 2021-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cognome', models.CharField(max_length=200)),
                ('data_nascita', models.DateField(verbose_name='data nascita')),
                ('NumTessera', models.IntegerField(default=0)),
                ('CodPersonale', models.IntegerField(default=0)),
            ],
        ),
    ]
